### ISSUE TITLE
v10.1 版本 卡在百灵不动

### ISSUE THREAD

**Issue by q123458384** [dundunnp/hamibot-auto_xuexiqiangguo#107]
QG版本：2.32.0
开启脚本后会自动进入积分页面，然后返回到主页，点击百灵 然后就一直没反应了
日志如下
![7CB0C135659A7F2B8E423A3197C3443F](https://user-images.githubusercontent.com/37495419/147627728-6ebebfab-f2ca-43e6-9274-c9a78cec20c1.jpg)

**Comment by dundunnp** [comment]
将强国升级至最新版2.33.0

**Comment by lzyccybadu** [comment]
> 将强国升级至最新版2.33.0
http://106.87.73.195:49155/imtt.dd.qq.com/16891/apk/BAFB627624D0E93B97CAEAE0B2F65A11.apk?mkey=61cd0af438788a8e65170cfcc349719f&arrive_key=32237569822&fsname=cn.xuexi.android_2.33.0_23300.apk&cip=125.68.189.78&proto=http

**Comment by q123458384** [comment]
> 开启脚本后会自动进入积分页面，然后返回到主页，

好的谢谢
