### ISSUE TITLE
报告问题：大神，四人赛双人对战（无配置版）1.0本地ocr报错

### ISSUE THREAD

**Issue by 85524365** [dundunnp/hamibot-auto_xuexiqiangguo#118]
大神，感激感谢您的分享奉献，汇报如下

23:01:56.773/E: Thread[ScriptThread-0[61d308b84a87644c98eafeff.js] (Spawn-0),5]: TypeError: Cannot call method "click" of null (61d308b84a87644c98eafeff.js#15)
TypeError: Cannot call method "click" of null
at 61d308b84a87644c98eafeff.js:15:0

23:02:46.355/E: ReferenceError: "ocr" is not defined. (61d308b84a87644c98eafeff.js#77)
ReferenceError: "ocr" is not defined.
at ocr_api (61d308b84a87644c98eafeff.js:77:0)
at do_it (61d308b84a87644c98eafeff.js:119:0)
at 61d308b84a87644c98eafeff.js:155:0

**Comment by 85524365** [comment]
![image](https://user-images.githubusercontent.com/48896432/148170276-363f62c6-2159-4401-80d8-7f96a86c4416.png)

**Comment by dundunnp** [comment]
这个问题是由于你的hamibot版本过低导致的，你需要到hamibot的官网下载最新版的v1.1.0才能支持本地ocr功能
另外这个脚本已经弃用了，[四人赛双人对战单独版](https://hamibot.com/marketplace/sp1Lc)也是支持无配置的，你只需在配置里将是否增强选择为否就行

**Comment by 85524365** [comment]
> 这个问题是由于你的hamibot版本过低导致的，你需要到hamibot的官网下载最新版的v1.1.0才能支持本地ocr功能 另外这个脚本已经弃用了，[四人赛双人对战单独版](https://hamibot.com/marketplace/sp1Lc)也是支持无配置的，你只需在配置里将是否增强选择为否就行

谢谢大神
