### ISSUE TITLE
专项答题不自动跳过

### ISSUE THREAD

**Issue by hscui** [dundunnp/hamibot-auto_xuexiqiangguo#132]
第一次运行，然后我的专项以前都答完了，就看它一直向下翻翻翻翻，翻了快20分钟翻到底了，然后就卡在那边，快半小时一动不动。
这也太傻了点吧。
每周答题是不是也这样？

**Comment by dundunnp** [comment]
咱也不看下配置信息，咱也不看下别人之前提过的问题，咱也不看下脚本说明，唉，咱就是玩
