### ISSUE TITLE
四人赛5.0和主脚本11.0答题两三个以后就停止了

### ISSUE THREAD

**Issue by Gumary** [dundunnp/hamibot-auto_xuexiqiangguo#141]
一直在用华为配置，昨天之前好好的，今天更新以后就只能答两道或者三道题，日志显示已识别，但是不点击答案
[![7h6p9K.jpg](https://s4.ax1x.com/2022/01/22/7h6p9K.jpg)](https://imgtu.com/i/7h6p9K)

**Comment by dundunnp** [comment]
可能是强国软件更新的问题，下个星期一解决这个bug

**Comment by alikankan** [comment]
> 可能是强国软件更新的问题，下个星期一解决这个bug

我今天早上运行一切正常，因为昨天用百度输了，还是改为华为OCR
