### ISSUE TITLE
Hamibot下架了吗？

### ISSUE THREAD

**Issue by liudun111** [dundunnp/hamibot-auto_xuexiqiangguo#142]
Hamibot上没有了

**Comment by dundunnp** [comment]
有关的都被下架了，不过还是可以通过复制源码自己运行

**Comment by liudun111** [comment]
> 的都被架下了，不过还是可以通过复制源码自己运行的

感谢🙏大神的支持！👍

**Comment by paulthehan** [comment]
Push plus 请求是不是少了个参数呢？Template

**Comment by smresultwithout** [comment]
> 有关的都被下架了，不过还是可以通过复制源码自己运行

求教程。

**Comment by hyzc0000** [comment]
> 有关的都被下架了，不过还是可以通过复制源码自己运行

请问大神，如何复制运行呢

**Comment by dundunnp** [comment]
> > 有关的都被下架了，不过还是可以通过复制源码自己运行
> 
> 请问大神，如何复制运行呢

明天我会写个教程

**Comment by hyzc0000** [comment]
> > > 有关的都被下架了，不过还是可以通过复制源码自己运行
> > 
> > 
> > 请问大神，如何复制运行呢
> 
> 明天我会写个教程

感谢大神！还有个问题，今天我学习强国更新到2.34，结果发现脚本运行到订阅就不动了，hamibot用的是1.3测试版，求教原因

**Comment by McMug2020** [comment]
我修改了一版，见Issues #114 ，希望尽快推出作者的权威版本。

**Comment by smresultwithout** [comment]
> > 有关的都被下架了，不过还是可以通过复制源码自己运行
> 
> 请问大神，如何复制运行呢

试了下自己新建个脚本，传js，新建好之后再传json，发布就行了，能过审。发布成私有。我发布了个v10.11在测会不会出现v11.0的答几题就卡主的问题。

**Comment by McMug2020** [comment]
> > > 有关的都被下架了，不过还是可以通过复制源码自己运行
> > 
> > 
> > 请问大神，如何复制运行呢
> 
> 试了下自己新建个脚本，传js，新建好之后再传json，发布就行了，能过审。发布成私有。我发布了个v10.11在测会不会出现v11.0的答几题就卡主的问题。

看你说的好像还是用的哈密波特？感觉这也是一个方法呀😁

**Comment by smresultwithout** [comment]
> > > > 有关的都被下架了，不过还是可以通过复制源码自己运行
> > > 
> > > 
> > > 请问大神，如何复制运行呢
> > 
> > 
> > 试了下自己新建个脚本，传js，新建好之后再传json，发布就行了，能过审。发布成私有。我发布了个v10.11在测会不会出现v11.0的答几题就卡主的问题。
> 
> 看你说的好像还是用的哈密波特？感觉这也是一个方法呀grin

是的，老哥你的我也下了，试试

**Comment by luoyang871111** [comment]
> 有关的都被下架了，不过还是可以通过复制源码自己运行

感谢公布源码，好人呐

**Comment by luoyang871111** [comment]
> > > 有关的都被下架了，不过还是可以通过复制源码自己运行
> > 
> > 
> > 请问大神，如何复制运行呢
> 
> 试了下自己新建个脚本，传js，新建好之后再传json，发布就行了，能过审。发布成私有。我发布了个v10.11在测会不会出现v11.0的答几题就卡主的问题。

别发布了，改改参数直接跑就行了，不发布也能在任务里面选到

**Comment by paulthehan** [comment]
期待教程

**Comment by qazyzj1** [comment]
> 有关的都被下架了，不过还是可以通过复制源码自己运行

有没有hamibot 脚本的链接  或者你的群 现在都变成私密脚本了

**Comment by liudun111** [comment]
> > > 的都被架下了，不过还是可以通过复制源码自己运行的
> > 
> > 
> > 大神，如何复制运行呢
> 
> 明天我会写个教程

大神自己捣鼓了半天还是运行不起来，求大神给个教程。🙏
