### ISSUE TITLE
封号？

### ISSUE THREAD

**Issue by Kleverx** [dundunnp/hamibot-auto_xuexiqiangguo#145]
代码是公开的，宣传部也经常上这个网。
现在下架了hamibot，下一步会不会针对使用脚本的人着手封号呢？

**思路我都想好了：**
百度\华为OCR实名认证，获取姓名，手机号，
到学习强国查找对应姓名、手机号，

**封号完成。。。**

**Comment by McMug2020** [comment]
我也注意到过这个问题，OCR软件用的是另外一个手机号注册的但是也是自己的号，百度还刷脸认证了…
不过用偶尔用一下，答题用的本地OCR+手动作答，请从轻发落。😂

**Comment by McMug2020** [comment]
搭配使用 学习效果佳
最新版本v1.6.1 [学习小熊] 火狐 Chrome 360 Edge QQ PC端桌面浏览器扩展插件 扫码登录官网学习 Andriod/IOS设备均适用 办公室推荐
[https://lllllllllllll。lanzoul。com/b02un4mhe] 密码 8888

**Comment by hafans01** [comment]
感觉这个不好排查，很容易误伤，除非挨个查调用记录

**Comment by hafans01** [comment]
> 代码是公开的，宣传部也经常上这个网。 现在下架了hamibot，下一步会不会针对使用脚本的人着手封号呢？
> 
> **思路我都想好了：** 百度\华为OCR实名认证，获取姓名，手机号， 到学习强国查找对应姓名、手机号，
> 
> **封号完成。。。**

感觉这个不好排查，很容易误伤，除非挨个查调用记录

**Comment by liudun111** [comment]
> 代码是公开架下的人封号，宣传部现在也经常上这个网。
> 
> **思路我都想好：** \华为OCR实名认证，获取姓名，手机号， 到学习强国检索姓名、手机号，
> 
> **封号完成。。。**

你着说的什么意思？ 你要封吗？

**Comment by Kleverx** [comment]
> > 代码是公开的，宣传部也经常上这个网。 现在下架了hamibot，下一步会不会针对使用脚本的人着手封号呢？
> > **思路我都想好了：** 百度\华为OCR实名认证，获取姓名，手机号， 到学习强国查找对应姓名、手机号，
> > **封号完成。。。**
> 
> 感觉这个不好排查，很容易误伤，除非挨个查调用记录

现在都是智能化，你调用识别了什么，一查就知道了。
天天天的只识别学习强国的答题，肯定是作弊没跑了。

还记得刚开始用python在电脑网页学习的那批人被封号吗？

**Comment by liudun111** [comment]
@dundunnp  大神，可有风险？

**Comment by McMug2020** [comment]
目前网页版用[学习小熊]只浏览文章视频个人认为是没有任何风险的

**Comment by Mercury-hhn** [comment]
已经开始慌了

**Comment by liudun111** [comment]
有没有小伙伴被封了？  你说的好怕怕哈。

**Comment by McMug2020** [comment]
对了，最近偶然发现，软件有本地OCR功能的运行或是在线调用OCR时，强国APP都会偷偷启动和上传数据。请懂技术的大佬留意下。 @Kleverx

**Comment by dundunnp** [comment]
请不要“妖言惑众”啊
我讲一下技术原理吧

首先是通过手机获取屏幕截图，app确实可以检测出是否你截了图，但我觉得这很正常，我想截图能有啥问题，当然如果你承担不了这个小风险就另当别论

第二步，把截图的图片转换为base64编码，发送一个http请求给百度或华为（这步也是app不能检测到的），这就相当于你打开一个浏览器一样。有这么多人请求，何来排查一说。要是你说可以通过传给华为或百度的图片，看是不是跟学习QG有关，且先不说百度或华为方面是否愿意检测，假设愿意，但这里的图片都是经过二值化处理的，就是普通的文字，与学习QG毫无关联

**Comment by Kleverx** [comment]
> 请不要“妖言惑众”啊 我讲一下技术原理吧
> 
> 首先是通过手机获取屏幕截图，app确实可以检测出是否你截了图，但我觉得这很正常，我想截图能有啥问题，当然如果你承担不了这个小风险就另当别论
> 
> 第二步，把截图的图片转换为base64编码，发送一个http请求给百度或华为（这步也是app不能检测到的），这就相当于你打开一个浏览器一样。有这么多人请求，何来排查一说。要是你说可以通过传给华为或百度的图片，看是不是跟学习QG有关，且先不说百度或华为方面是否愿意检测，假设愿意，但这里的图片都是经过二值化处理的，就是普通的文字，与学习QG毫无关联

OCR返回的结果，明显是强国题库内的题。
天天天只识别这个
