### ISSUE TITLE
v11.0经常卡住，特别挑战答题。退回v10.11就很顺利可以搞定了。

### ISSUE THREAD

**Issue by smresultwithout** [dundunnp/hamibot-auto_xuexiqiangguo#146]
从github下了一个旧版传到hamibot试了下，一次刷完。建议作者可以看看11版本是什么问题，应该不是学习软件更新问题。

**Comment by guantou2009** [comment]
> 从github下了一个旧版传到hamibot试了下，一次刷完。建议作者可以看看11版本是什么问题，应该不是学习软件更新问题。

旧版怎么下啊？

**Comment by dundunnp** [comment]
> 从github下了一个旧版传到hamibot试了下，一次刷完。建议作者可以看看11版本是什么问题，应该不是学习软件更新问题。

你可以再试下v11，那天应该是某个题库网站挂了
