### ISSUE TITLE
OCR识别标点符号出错的终极办法

### ISSUE THREAD

**Issue by Kleverx** [dundunnp/hamibot-auto_xuexiqiangguo#148]
![hecheng](https://user-images.githubusercontent.com/51278166/150677278-1580edc5-15a9-4459-99aa-8b48d9399030.jpg)
那就是不要标点符号，
目前使用很好

**Comment by dundunnp** [comment]
我访问的是网络上的题库，不是自己的题库
另外其实标点符号可以用一行代码去掉的
![14CD95BB](https://user-images.githubusercontent.com/68000706/150898537-66f9b949-eccb-46de-b821-31062800c524.png)

**Comment by Kleverx** [comment]
> 我访问的是网络上的题库，不是自己的题库 另外其实标点符号可以用一行代码去掉的 ![14CD95BB](https://user-images.githubusercontent.com/68000706/150898537-66f9b949-eccb-46de-b821-31062800c524.png)

应该是的，我还是从有了学习强国后才开始学着写代码的。。。
一路摸索，太曲折了
还有一行的话怎么写｡◕‿◕｡

**Comment by dundunnp** [comment]
你可以了解一下正则表达式
