### ISSUE TITLE
V11卡在订阅不动，强国版本2.34.0，hamibot版本1.1.0

### ISSUE THREAD

**Issue by hyzc0000** [dundunnp/hamibot-auto_xuexiqiangguo#151]
前几天不小心升级了学习强国到2.34.0，原先能运行正常的订阅现在到了强国号界面就不动了，请教解决办法。[](url
![微信图片_20220126153338](https://user-images.githubusercontent.com/36850286/151121973-0c519e3e-551d-4da4-bbea-f7a851c48238.jpg)
)

**Comment by dundunnp** [comment]
我已经放了v2.33.0的安装包在github

**Comment by hyzc0000** [comment]
> 我已经放了v2.33.0的安装包在github

感谢，那我去重新安装一下

**Comment by McMug2020** [comment]
豌豆荚有下载历史版本，不勾选选择普通下载
https://m。wandoujia。com/apps/7920908/history_v23300
dots改成句号，不用改回来直接复制到浏览器打开
