### ISSUE TITLE
文章阅读完成后脚本会停在“电台”页面不继续进行其他任务，需要重新执行一遍脚本才能继续。

### ISSUE THREAD

**Issue by AnonyEastRainbow** [dundunnp/hamibot-auto_xuexiqiangguo#158]
设备：红米K20Pro
安卓版本：Android 9
MIUI版本：MIUI 10 开发版 9.8.1
文章阅读完成后，脚本会停在“电台”页面，不继续进行其他任务，需要重新执行一遍脚本才能继续。在日志中看不到任何报错，也没有显示运行结束，不知道是什么原因，很难排查。

**Comment by dundunnp** [comment]
可能是android版本太低等原因吧

**Comment by hafans01** [comment]
我最近几天也遇到这个问题了，没排查出来原因

**Comment by dundunnp** [comment]
今天测试了一下好像是存在这个问题.....后续版本我会修复的

**Comment by AnonyEastRainbow** [comment]
谢谢，目前没有这个问题了
