### ISSUE TITLE
脚本订阅功能的问题

### ISSUE THREAD

**Issue by McMug2020** [dundunnp/hamibot-auto_xuexiqiangguo#165]
测试版本：强国App 2.31.0和2.33.0，鸿蒙2.0
订阅行为在强国号就结束了，并未浏览地方平台
同时因订阅过程耗时较多，建议增加设置选项 [2021年以前的订阅是否已完成]，或者像WYQG那样初始遍历一遍 后续只访问2022上线的订阅
请拔冗解答下，十分感谢！@dundunnp

**Comment by dundunnp** [comment]
感谢建议，目前脚本确实没有考虑地方平台，后续版本会增加
确实考虑到订阅过程耗时太大，会增加这个设置选项
想问一下WYQG是怎么做到这个技术的，我以为每次运行脚本都是一个独立的过程，不能之间通信啊

**Comment by McMug2020** [comment]
是我记错了，WYQG订阅没有这个功能，是专项答题，脚本没给自定义设置，专项答题翻过了一遍下次运行就不会从头来过
想想订阅有这个也没什么用，2021年以前的答完后能手动设置就行了，并且订阅栏目肯定还会变动改太多意义不大。

**Comment by songgedodo** [comment]
> 感谢建议，目前脚本确实没有考虑地方平台，后续版本会增加 确实考虑到订阅过程耗时太大，会增加这个设置选项 想问一下WYQG是怎么做到这个技术的，我以为每次运行脚本都是一个独立的过程，不能之间通信啊
用了hamibot的本地存储模块storages，可以每次先读取缓存变量。或者不使用该方法，通过脚本在本地保存一个文件，这样甚至可以手动转移历史配置

**Comment by dundunnp** [comment]
good idea！thanks

**Comment by McMug2020** [comment]
测试版本：强国App 2.31.0和2.33.0，鸿蒙2.0
作者您好，烦请检查下之前的订阅已完成选项，是不是两个Tab都没定位到 2022年上线 按钮啊？谢谢 @dundunnp

**Comment by dundunnp** [comment]
> 测试版本：强国App 2.31.0和2.33.0，鸿蒙2.0 作者您好，烦请检查下之前的订阅已完成选项，是不是两个Tab都没定位到 2022年上线 按钮啊？谢谢 @dundunnp

是的，软件新增加了一个模块，下个版本将会更新
