### ISSUE TITLE
建议分享功能能与阅读文章独立

### ISSUE THREAD

**Issue by McMug2020** [dundunnp/hamibot-auto_xuexiqiangguo#173]
目前v12.0脚本已臻完美了，希望分享能与阅读文章独立开来，已便在手机App上浏览文章已满分了或PC端学习完文章视频后可以实现分享的功能，感谢。@dundunnp
我试过同一篇文章可以分享两次并得分，可以在发表观点时分享两次。

**Comment by dundunnp** [comment]
好的

**Comment by McMug2020** [comment]
辛苦您了！！
