### ISSUE TITLE
新版本更新地址

### ISSUE THREAD

**Issue by hujinchaopk** [dundunnp/hamibot-auto_xuexiqiangguo#177]
我用蓝奏浏览器分享了[自动学习_v1.4], 下载链接:https://wwr.lanzoui.com/iDT7T0087zij 提取码 : d78c, 你可以不限速下载哦
学习强国和法宣在线 自动学习，强国多用户版本测试十个账号无卡顿。每天42-44分左右，单个账号运行时间19分钟完成

**Comment by Sharkkkk** [comment]
想钱想疯了吗

**Comment by dundunnp** [comment]
> 想钱想疯了吗

你好，我想问下这个是要付费的吗，如果是我会立马删除这个issue的

**Comment by Sharkkkk** [comment]
对的，来别人帖子下打广告，还是付费的，太过分了吧

**Comment by Sharkkkk** [comment]
> > 想钱想疯了吗
> 
> 你好，我想问下这个是要付费的吗，如果是我会立马删除这个issue的

对的，来别人帖子下打广告，还是付费的，太过分了吧
