### ISSUE TITLE
模拟器报错

### ISSUE THREAD

**Issue by ZrSamuel** [dundunnp/hamibot-auto_xuexiqiangguo#191]
TypeError: Cannot call method "child" of null (621ebda348d00acd0af73b6d.js#195)

**Comment by McMug2020** [comment]
目前hamibot内置OCR不太适配模拟器，像Study、WYQG有第三方OCR勉强能运行，浩然OCR

**Comment by ZrSamuel** [comment]
a

**Comment by ZrSamuel** [comment]
> 模拟器是存在这个问题，你可以看看之前的issue，他们是怎么配置的

老哥 能帮我把这个issue删除下吗

**Comment by ZrSamuel** [comment]
@[dundunnp](https://github.com/dundunnp)
