### ISSUE TITLE
经常在阅读文章和视频看完后卡在积分页面或者电台

### ISSUE THREAD

**Issue by TT7even** [dundunnp/hamibot-auto_xuexiqiangguo#196]
三星S10
Android 11
ONE UI 3.1

**Comment by McMug2020** [comment]
![Screenshot_20220305_171129](https://user-images.githubusercontent.com/92876629/156876845-fce1f740-d6c9-4752-b6c1-0504f444f67e.jpg)
可能是软件版本的问题。完美运行还是要用v2.33.0版本，我刚试了有63分。

豌豆荚有下载历史版本，不勾选选择普通下载
[https://m。wandoujia。com/apps/7920908/history_v23300]
dots改成句号，不用改回来直接复制到浏览器打开

**Comment by TT7even** [comment]
> ![Screenshot_20220305_171129](https://user-images.githubusercontent.com/92876629/156876845-fce1f740-d6c9-4752-b6c1-0504f444f67e.jpg) 可能是软件版本的问题。完美运行还是要用v2.33.0版本，我刚试了有63分。
> 
> 豌豆荚有下载历史版本，不勾选选择普通下载 [https://m。wandoujia。

**Comment by TT7even** [comment]
好的谢谢 @McMug2020
