### ISSUE TITLE
关于获取题干问题解决

### ISSUE THREAD

**Issue by liubaba0212** [dundunnp/hamibot-auto_xuexiqiangguo#203]
您好，偶然看到您的项目，很厉害。
看到您的项目使用的是ocr获取题干，错误率高。我之前也做过一个类似的app答题脚本，python配合appium写的，建议您可以看一下appium这个技术，可以从界面上直接获取题干，及一些文字。我技术太菜了，还达不到直接贡献代码的程度，还望海涵。

**Comment by liubaba0212** [comment]
![image](https://user-images.githubusercontent.com/75424838/158119085-47d7b8b9-30f6-4f29-ac67-419aac0520e8.png)
刚刚试了一下，是可以直接获取文本的。

**Comment by Edward88888888** [comment]
好像四人赛和双人赛不可以。

**Comment by liubaba0212** [comment]
> 好像四人赛和双人赛不可以。
是的，刚刚看了下。
