### ISSUE TITLE
四人对答报错 No implementation found for long

### ISSUE THREAD

**Issue by anby1** [dundunnp/hamibot-auto_xuexiqiangguo#205]
![微信图片_20220315210920](https://user-images.githubusercontent.com/66161710/158384646-76425e00-105c-4695-bc38-c210e5fe0a7e.png)

**Comment by dundunnp** [comment]
手机可能太老了吧，不支持这个功能

**Comment by 79133576** [comment]
> 

谢谢作者大大这么快回复我!

**Comment by syncake** [comment]
问题+1

机型华为荣耀8A，操作系统9.1
直接报错，调试机会都不给
