### ISSUE TITLE
官方调整答题选项为随机顺序了，需修复

### ISSUE THREAD

**Issue by McMug2020** [dundunnp/hamibot-auto_xuexiqiangguo#206]
今天下午时候官方调整挑战答题、四人赛双人对战选项为随机顺序，脚本需要修复，不然会答错的！
另外订阅栏目 未点击的问题也希望抽空解决，感谢😊

**Comment by yaohongbin2007** [comment]
我也遇到了，挑战答题一直在错

**Comment by dundunnp** [comment]
收到问题，我会尽快修复的，大家在新版本发布之前只能先手动完成挑战答题、四人赛双人对战答题了

**Comment by Edward88888888** [comment]
> 收到问题，我会尽快修复的，大家在新版本发布之前只能先手动完成挑战答题、四人赛双人对战答题了

麻烦顺便题库也更新一下呀。。最好是本地题库。网络题库速度和正确率还是有所欠缺。

**Comment by zhufscug** [comment]
后续答案选项也要OCR了，一天OCR次数估计要上百了，每月1000次免费OCR不够了吧

**Comment by dundunnp** [comment]
> 后续答案选项也要OCR了，一天OCR次数估计要上百了，每月1000次免费OCR不够了吧

选项ocr调用的都是hamibot自带的ocr，不会消耗1000次里面的，后续增加的功能也是尽量能用自带的就用自带的，可以放心，如果后续消耗1000次有我也会提前说明的

**Comment by dundunnp** [comment]
> 

订阅的问题不是已经解决了吗

**Comment by raawaa** [comment]
谢谢 @dundunnp 回复这么迅速，现在每天的积分就全靠你了。

**Comment by dundunnp** [comment]
新版本v13.0已经解决了此问题，四人赛双人对战单独脚本也已更新，请各位及时更新代码
由于官网将选项打乱顺序，因此需要识别（用的是hamibot自带ocr，并不消耗百度或华为的次数）每个选项，因此答题的时间增加了，不能做到秒答了，所以如果想拿第一的话请酌情考虑使用脚本

**Comment by 79133576** [comment]
> 新版本v13.0已经解决了此问题，四人赛双人对战单独脚本也已更新，请各位及时更新代码 由于官网将选项打乱顺序，因此需要识别（用的是hamibot自带ocr，并不消耗百度或华为的次数）每个选项，因此答题的时间增加了，不能做到秒答了，所以如果想拿第一的话请酌情考虑使用脚本

大佬，13.0的挑战答题做了三题就没做下去了，也没上一个版本的分享复活功能

**Comment by raawaa** [comment]
@79133576 你试试我自己魔改的版本：
https://github.com/raawaa/hamibot-auto_xuexiqiangguo/blob/fix/random_answer/%E5%AD%A6%E4%B9%A0%E5%BC%BA%E5%9B%BD.js

看看哪个效果好。欢迎反馈！

**Comment by McMug2020** [comment]
> @79133576 你试试我自己魔改的版本： https://github.com/raawaa/hamibot-auto_xuexiqiangguo/blob/fix/random_answer/%E5%AD%A6%E4%B9%A0%E5%BC%BA%E5%9B%BD.js
> 
> 看看哪个效果好。欢迎反馈！

您这个好像不是在v13.0的基础上改的吧

**Comment by raawaa** [comment]
> > @79133576 你试试我自己魔改的版本： https://github.com/raawaa/hamibot-auto_xuexiqiangguo/blob/fix/random_answer/%E5%AD%A6%E4%B9%A0%E5%BC%BA%E5%9B%BD.js
> > 看看哪个效果好。欢迎反馈！
> 
> 您这个好像不是在v13.0的基础上改的吧

是我昨晚临时改的，当时v13.0还没出。
功能上跟v13.0类似，但是挑战答题没有通过OCR，而是直接拾取选项文字。所以速度和准确率可能更好一点。

**Comment by dundunnp** [comment]
> > 新版本v13.0已经解决了此问题，四人赛双人对战单独脚本也已更新，请各位及时更新代码 由于官网将选项打乱顺序，因此需要识别（用的是hamibot自带ocr，并不消耗百度或华为的次数）每个选项，因此答题的时间增加了，不能做到秒答了，所以如果想拿第一的话请酌情考虑使用脚本
> 
> 大佬，13.0的挑战答题做了三题就没做下去了，也没上一个版本的分享复活功能

啊？不会吧，我测试了好多次都可以正常运行

**Comment by McMug2020** [comment]
> 

谢谢大佬，我升级v13.0和hamibot1.3.1后订阅确实正常了。

**Comment by dundunnp** [comment]
> @79133576 你试试我自己魔改的版本： https://github.com/raawaa/hamibot-auto_xuexiqiangguo/blob/fix/random_answer/%E5%AD%A6%E4%B9%A0%E5%BC%BA%E5%9B%BD.js
> 
> 看看哪个效果好。欢迎反馈！

很棒！！

**Comment by 79133576** [comment]
@raawaa 完美诠释了为人民服务的宗旨

**Comment by McMug2020** [comment]
Hamibot自用学习脚本，同步更新v13.0，小号测试完成63分
[https://hamibot。com/marketplace/gtf52?invite=ADfZFZnW31U9Xrnu7xy8Ns3U]
dots改成句号，不用改回来直接复制到浏览器打开

**Comment by iChoix** [comment]
提问 看到大佬用的是本地ocr 那意思是不是就不要勾选提高正确率用的华为ocr和相关配置了？

**Comment by dundunnp** [comment]
> 提问 看到大佬用的是本地ocr 那意思是不是就不要勾选提高正确率用的华为ocr和相关配置了？

选项的识别较为简单，而且太多没必要用，但是还是需要华为或百度ocr去识别题目的

**Comment by iChoix** [comment]
> 

就是还是需要配置第三方ocr来识别我的理解对吗，小白问题可能比较低级大佬勿怪

**Comment by iChoix** [comment]
> > 提问 看到大佬用的是本地ocr 那意思是不是就不要勾选提高正确率用的华为ocr和相关配置了？
> 
> 选项的识别较为简单，而且太多没必要用，但是还是需要华为或百度ocr去识别题目的

就是还是需要配置第三方ocr来识别我的理解对吗，小白问题可能比较低级大佬勿怪

**Comment by dundunnp** [comment]
> > > 提问 看到大佬用的是本地ocr 那意思是不是就不要勾选提高正确率用的华为ocr和相关配置了？
> > 
> > 
> > 选项的识别较为简单，而且太多没必要用，但是还是需要华为或百度ocr去识别题目的
> 
> 就是还是需要配置第三方ocr来识别我的理解对吗，小白问题可能比较低级大佬勿怪

嗯，也可以选择不配置，你可以对比一下

**Comment by iChoix** [comment]
> 



> > > > 提问 看到大佬用的是本地ocr 那意思是不是就不要勾选提高正确率用的华为ocr和相关配置了？
> > > 
> > > 
> > > 选项的识别较为简单，而且太多没必要用，但是还是需要华为或百度ocr去识别题目的
> > 
> > 
> > 就是还是需要配置第三方ocr来识别我的理解对吗，小白问题可能比较低级大佬勿怪
> 
> 嗯，也可以选择不配置，你可以对比一下

![image](https://user-images.githubusercontent.com/6520601/159109127-38775628-060a-46fb-8356-d727f4765ee6.png)

**Comment by McMug2020** [comment]
答题实测比隔壁慢了一些，隔壁使用了下载到本地的离线题库（启动时会检查题库更新），同样识别慢下来后优势明显了

**Comment by alikankan** [comment]
> @79133576 你试试我自己魔改的版本： https://github.com/raawaa/hamibot-auto_xuexiqiangguo/blob/fix/random_answer/%E5%AD%A6%E4%B9%A0%E5%BC%BA%E5%9B%BD.js
> 
> 看看哪个效果好。欢迎反馈！

你这个效果真的好，目前比dundun的最新版速度快 ，就算不开增强识别都能赢 ，希望更多人看到

**Comment by raawaa** [comment]
> 答题实测比隔壁慢了一些，隔壁使用了下载到本地的离线题库（启动时会检查题库更新），同样识别慢下来后优势明显了

隔壁是哪里能透露吗，我也去试试。

**Comment by raawaa** [comment]
提交了个PR：https://github.com/dundunnp/hamibot-auto_xuexiqiangguo/pull/207
根据我昨晚自己魔改的内容，对原作者的v13.0进行了一点优化。挑战答题不再通过OCR，而是直接获取选项内容，提高了答题速度和成功率。

**Comment by McMug2020** [comment]
> > 答题实测比隔壁慢了一些，隔壁使用了下载到本地的离线题库（启动时会检查题库更新），同样识别慢下来后优势明显了
> 
> 隔壁是哪里能透露吗，我也去试试。

已经不重要了，答题的逻辑又改了，挑战答题的那部分可以保留
下午答题的逻辑又改了，四人赛双人对战恢复以前的固定选项了，现在挑战答题选项还是打乱的

**Comment by raawaa** [comment]
> > > 答题实测比隔壁慢了一些，隔壁使用了下载到本地的离线题库（启动时会检查题库更新），同样识别慢下来后优势明显了
> > 
> > 
> > 隔壁是哪里能透露吗，我也去试试。
> 
> 已经不重要了，答题的逻辑又改了，挑战答题的那部分可以保留 下午答题的逻辑又改了，四人赛双人对战恢复以前的固定选项了，现在挑战答题选项还是打乱的

我不打算改回来了。固定选项毕竟不保险。最好的方式还是通过答案内容来答题。
我试下来，目前速度和准确率的瓶颈主要还是离线题库上。

**Comment by McMug2020** [comment]
对对对，可能周一又改了这谁受得了啊，没仔细看原来您是在v13.0的基础上又改了一版@[raawaa](https://github.com/raawaa)

**Comment by McMug2020** [comment]
根据[raawaa](https://github.com/raawaa)大佬提交的PR#207又更新了一版
[https://hamibot。com/marketplace/gtf52?invite=ADfZFZnW31U9Xrnu7xy8Ns3U]
dots改成句号，不用改回来直接复制到浏览器打开

**Comment by raawaa** [comment]
自己尝试了一下，在最新版的基础上增加了本地题库的功能。题库利用的是别人的github项目。

但是目前比较简陋，需要自己手动下载题库文件到手机内存里。把 [Mondayfirst/XXQG_TiKu: 学习强国_挑战答题题库](https://github.com/Mondayfirst/XXQG_TiKu) 项目下的`题库_原始版.json`文件下载到手机内部存储根目录 `Download` 文件夹下。

脚本会自动识别是否存在本地题库。若不存在，仍会使用在线题库答题。

脚本下载：https://github.com/raawaa/hamibot-auto_xuexiqiangguo/blob/enhancement/local_question_bank/%E5%AD%A6%E4%B9%A0%E5%BC%BA%E5%9B%BD.js

查询本地题库用的是最笨的遍历的方法，查询效率有很大的提升空间。但是本人不是职业搞程序的，水平有限。

**Comment by McMug2020** [comment]
十分感谢！本地题库肯定要稳点。

**Comment by dundunnp** [comment]
感谢[raawaa](https://github.com/raawaa)这么辛勤的付出！激发了懒惰的我  明天把本地题库搞定吧（如果没意外的话
我会将本地题库通过http下载而不是手动，然后查询效率用算法优化一下
感谢大家共同维护脚本！！

**Comment by McMug2020** [comment]
官方客服：答题选项乱序方式，技术原因紧急下线，晚些时候会再次上线，请您持续关注…🦇了   @raawaa @dundunnp
