### ISSUE TITLE
脚本运行后，Hamibot退出

### ISSUE THREAD

**Issue by er7x** [dundunnp/hamibot-auto_xuexiqiangguo#212]
Hamibot版本：1.3.1
学习强国版本：2.33
安卓版本：11
问题描述：运行脚本后，Hamibot会被关闭，导致脚本运行停止。

**Comment by alikankan** [comment]
你要把hamibot日志贴出来才好确定，或许你设置或权限问题，因为我执行是正常的

**Comment by er7x** [comment]
日志没有内容，因为一执行就退出了。

**Comment by dundunnp** [comment]
Hamibot会被关闭是啥意思？后台被杀吗？
把hamibot的后台权限打开，然后看看你的手机是不是有防止软件点击的安全措施，关闭它

**Comment by er7x** [comment]
我推测不是后台被杀了，应该是手机系统与Hamibot V1.3.1的兼容性问题。是运行错误退出了

**Comment by hscui** [comment]
目前这个版本（V14.0)是执行后跳到无障碍里面去了，我已经设置了无障碍，但它就是一直跳过去；用不了。

**Comment by dundunnp** [comment]
> 目前这个版本（V14.0)是执行后跳到无障碍里面去了，我已经设置了无障碍，但它就是一直跳过去；用不了。

![image](https://user-images.githubusercontent.com/68000706/159265986-2789edeb-c634-4061-9a48-caac0d878a42.png)

**Comment by er7x** [comment]
反馈使用情况，我换了一部高性能手机，没有再出现Hamibot出错退出的问题。推没是本地OCR对手机性能有要求，我之前用的那部手机性能差，导致运行出错。
