### ISSUE TITLE
提高脚本对战速度的几点建议

### ISSUE THREAD

**Issue by McMug2020** [dundunnp/hamibot-auto_xuexiqiangguo#226]
目前脚本的对战速度比隔壁慢很多。经过实战测试和横向对比，原因是作答逻辑还是应该先识别题目，再识别选项才行。具体建议如下：
    1、取消在线的第三方OCR，只使用内置的OCR进行识别。(OCR次数多了免费不够用了，可以通过答错降低排名弥补；本地第三方浩然OCR比内置的要慢也不建议用；浮窗显示手动答的话，答案简单还好，看着长的选项已经反应不过来了)
    2、建议把答错脚本整合到主脚本和单独对战（答题慢后已不得已选做），在完成对战后运行，配置中自行选择是否启用、间隔时间和次数。
    3、只使用本地题库，要稳一点，脚本启动后检测更新和下载。

**Comment by 2uschauer** [comment]
现在还有别家能做到这个程度么

**Comment by zlhdd108** [comment]
现在的正确率也不高吧……早上基本上都是错好多，大部分题目出来就选了第一项，然后就错了，速度倒是不慢

**Comment by babi-Q** [comment]
总听到隔壁，隔壁到底在哪儿呀。
现在的对战，有时候秒选错答案，有时候要好久才选到正确答案。我看百度后台也有成功调用ocr。

**Comment by babi-Q** [comment]
> 现在的正确率也不高吧……早上基本上都是错好多，大部分题目出来就选了第一项，然后就错了，速度倒是不慢

我也是这样，都是秒选第一选项。

**Comment by KeenM6** [comment]
是的，升级了14.0和14.1以后答题错误率增加，速度变慢。

**Comment by eaglexxxm** [comment]
> 总听到隔壁，隔壁到底在哪儿呀。
> 现在的对战，有时候秒选错答案，有时候要好久才选到正确答案。我看百度后台也有成功调用ocr。

详细的后台怎么看呢？
