### ISSUE TITLE
主脚本跟单独四人赛同样错误-----Hamibot:错误：TypeError: Cannot call mathod "child" of null (61a................js#29)

### ISSUE THREAD

**Issue by luoxuye** [dundunnp/hamibot-auto_xuexiqiangguo#28]
首先感谢大佬单独出的四人赛功能，
不过最新版本的主脚本跟四人赛到答题那里就报错了，不能用，提示这个错误。

**Comment by luoxuye** [comment]
![(~1CHEJ4NX5J$) AQV2QAX2](https://user-images.githubusercontent.com/42453877/144711050-5d9f5b15-ed4a-4f78-bef1-6c9878634285.jpg)

**Comment by dundunnp** [comment]
新版本v2.0解决了这个问题

**Comment by luoxuye** [comment]
> 

一直在刷新，好像2.0更新了。还是有这个问题。

**Comment by KeyBoxing** [comment]
主脚本，正常四人赛结束后，双人赛报错
00:33:06.590/D:2.在2018年平昌冬季奥林匹克
运动会上，为中国赢得首枚金牌的运动员
00:33:09.145/D:3.改革开放新阶段，涌现出
大批优秀共产党员。
00:33:11.199/D：3.改革开放新阶段，涌现出
大批优秀共产党员。
00:33:13.141/D:4.选择词语的正确词形
00:33:15.086/D：4.选择词语的正确词形B.消弥
00:33:27.187/E: TypeError:
Cannot call method "click" of null
(61ab512667479173a3cab7d1.is#245)
TypeError: Cannot call method "click" of null
at 61ab52667479173a3cab7d1 .js:245:0

**Comment by gitgithubhub1dot** [comment]
此外，主脚本在每日答题中，如果出现填空题输入错误后，会退出每日答题到学习积分界面，然后进入点点通界面并且一直停在此页面。通过停止脚步，再运行，每日答题正确后，又可正常继续

**Comment by dundunnp** [comment]
> 此外，主脚本在每日答题中，如果出现填空题输入错误后，会退出每日答题到学习积分界面，然后进入点点通界面并且一直停在此页面。通过停止脚步，再运行，每日答题正确后，又可正常继续

我会解决这个bug的

**Comment by dundunnp** [comment]
> > 
> 
> 一直在刷新，好像2.0更新了。还是有这个问题。



> 主脚本，正常四人赛结束后，双人赛报错 00:33:06.590/D:2.在2018年平昌冬季奥林匹克 运动会上，为中国赢得首枚金牌的运动员 00:33:09.145/D:3.改革开放新阶段，涌现出 大批优秀共产党员。 00:33:11.199/D：3.改革开放新阶段，涌现出 大批优秀共产党员。 00:33:13.141/D:4.选择词语的正确词形 00:33:15.086/D：4.选择词语的正确词形B.消弥 00:33:27.187/E: TypeError: Cannot call method "click" of null (61ab512667479173a3cab7d1.is#245) TypeError: Cannot call method "click" of null at 61ab52667479173a3cab7d1 .js:245:0

新版本v2.1已经延长了时间，这个bug应该会的到修复
