### ISSUE TITLE
"words_block_list" 

### ISSUE THREAD

**Issue by lzyccybadu** [dundunnp/hamibot-auto_xuexiqiangguo#35]
TypeError: Cannot read property "words_block_list" from undefined]

**Comment by qianoix** [comment]
是不是刚改名，改名有延迟，成功改名后domainname要更新一下

**Comment by lzyccybadu** [comment]
名字无修改，估计是需要付费原因，一年45

**Comment by yingloufei** [comment]
一样的显示

**Comment by lzyccybadu** [comment]
> 一样的显示

更新版本后已经解决
