### ISSUE TITLE
小米9，运行报错 typeError Cannot read property 

### ISSUE THREAD

**Issue by zl9903204** [dundunnp/hamibot-auto_xuexiqiangguo#36]
大大求解   小米9，运行报错 TypeError Cannot read property “word block list” from undefined

**Comment by heilongshanke** [comment]
HUAWEI Mate 30. The same issue.

**Comment by thank243** [comment]
mate20
 
> 10:59:25.187/D: [TypeError: Cannot read property "words_block_list" from undefined]

**Comment by Zypeong** [comment]
红米K40也是呀

**Comment by zl9903204** [comment]
问题解决了，我自己犯的弱智错误，我第一次开启OCR服务是在华北服务器上，后来觉得华东服务器可能更快，HAMIBOT就配置的华东服务器，但是没意识到华东服务器还要再开一次OCR。。。。

**Comment by lwh201314** [comment]
我是换了一个区域就可以了，之前用北京4一直是这个错误
