### ISSUE TITLE
需付费45元才可以使用ocr了

### ISSUE THREAD

**Issue by i-fengma** [dundunnp/hamibot-auto_xuexiqiangguo#37]
根据作者的教程，浏览到：文字识别->网络图片识别这里（https://console.huaweicloud.com/ocr/），发现需要付费45元才可以开通使用1年。
我看作者的教程是可以免费使用的。
所以，等免费的ocr了……
最后，感谢作者的付出！

**Comment by 79133576** [comment]
https://www.huaweicloud.com/pricing.html?tab=detail#/ocr

![image](https://user-images.githubusercontent.com/66161710/144792124-eb92c8c3-a77b-4272-9754-6bf6eaf511f6.png)

**Comment by i-fengma** [comment]
> https://www.huaweicloud.com/pricing.html?tab=detail#/ocr
> 
> ![image](https://user-images.githubusercontent.com/66161710/144792124-eb92c8c3-a77b-4272-9754-6bf6eaf511f6.png)

为何我文字识别->网络图片识别 那里不可以选择按需付费呢？没有那个选项。谢谢答复！

<img width="945" alt="截屏2021-12-06 下午2 13 04" src="https://user-images.githubusercontent.com/20429317/144796939-ba5af1bc-cbf7-458e-b79b-b74d04e4d70c.png">
<img width="896" alt="截屏2021-12-06 下午2 15 52" src="https://user-images.githubusercontent.com/20429317/144796959-39db9510-c555-49fb-bd11-645a6d62d24f.png">

**Comment by thank243** [comment]
你看下是不是有其他服务导致账号欠费了。

**Comment by i-fengma** [comment]
> 你看下是不是有其他服务导致账号欠费了。

是新建的账号。没有欠费。

**Comment by lzyccybadu** [comment]
> > 你看下是不是有其他服务导致账号欠费了。
> 
> 是新建的账号。没有欠费。

me too

**Comment by 79133576** [comment]
你华为云实名认证了吗？

**Comment by lzyccybadu** [comment]
> 你华为云实名认证了吗？

是的

**Comment by 79133576** [comment]
> > 你华为云实名认证了吗？
> 
> 是的

原因分析
可能是因为当前使用的是IAM用户，IAM用户没有开通服务的权限。账号与IAM用户可以类比为父子关系，账号是资源归属以及计费的主体，对其拥有的资源具有所有权限。

解决措施
使用账号登录OCR控制台，开通服务。

**Comment by lzyccybadu** [comment]
> > > 你华为云实名认证了吗？
> > 
> > 
> > 是的
> 
> 原因分析 可能是因为当前使用的是IAM用户，IAM用户没有开通服务的权限。账号与IAM用户可以类比为父子关系，账号是资源归属以及计费的主体，对其拥有的资源具有所有权限。
> 
> 解决措施 使用账号登录OCR控制台，开通服务。

套餐基础包是年计费，100/年，阶梯价格是每月免费1000次，应该是在年计费基础上免费，所以目前不行的应该是近段时间开通OCR的都要100或45，另外百度OCR也是需要付费

**Comment by lzyccybadu** [comment]
OCR基础在手机端华为云界面有活动，0元支付后即可，双人、四人已经更新版本，经测试，已经修复了第1题需要手动的BUG

**Comment by i-fengma** [comment]
万般无奈之下换了个手机号来注册。神奇的发现，竟然没有这个问题了！
推荐和我问题一致的试试！
