### ISSUE TITLE
能不能只做四人对战答题啊。

### ISSUE THREAD

**Issue by luoxuye** [dundunnp/hamibot-auto_xuexiqiangguo#7]
其他的可以自己做
 4人赛不好拿分，想只要这一个功能，
点一次完成一次四人赛，不用做其他的，也不用管四人赛有没有做。

**Comment by luoxuye** [comment]
同样也可以测试一下答题功能，现在只能做全套。完成了的就不做的话，根本不知道答题有没有效，，，

**Comment by dundunnp** [comment]
> 

如果你其他的都已经拿到了满分，那么其他模块就不会执行

**Comment by luoxuye** [comment]
是这样没错，但是我只想保证能拿到4人赛满分，4人赛做完以后 也不会再执行，用小号测试的不行，但是也只有一次机会。。。。第二次就测试不了额，又不敢拿大号试，大号也只有一次机会

**Comment by dundunnp** [comment]
保证拿满分目前是不太可能的，第一可能题库搜不到题，第二ocr可能没有获取到题目，很难保证每次都第一，如果你有特殊需求需要拿满分，抱歉这个脚本貌似不能满足

**Comment by luoxuye** [comment]
当然不会要求把把第一，至少不是乱答就行了

**Comment by luoxuye** [comment]
现在的情况是把把稳定1分，仅仅是能完成的级别。。。

**Comment by Nohack2012** [comment]
安卓7好像不行，进入获取积分，马上back两次回到主界面就不动了

**Comment by dundunnp** [comment]
> 当然不会要求把把第一，至少不是乱答就行了

当然不是乱答，具体说明与解决方法我会和下个版本一起发布

**Comment by dundunnp** [comment]
> 安卓7好像不行，进入获取积分，马上back两次回到主界面就不动了

可能原因是填写的省份不正确

**Comment by luoxuye** [comment]
唉，反正我就想把这个功能单独拿出来，不然不知道能不能用。。。其他功能还好，无限试错。这个就一2次机会。没得测试空间。

**Comment by squallwind** [comment]
> 唉，反正我就想把这个功能单独拿出来，不然不知道能不能用。。。其他功能还好，无限试错。这个就一2次机会。没得测试空间。

你这是要搞学习标兵?力争排行榜第一?

**Comment by sancy99** [comment]
建议能自己选做哪些，这样也方便测试功能

**Comment by dundunnp** [comment]
我已经发布单独测试[四人赛和双人对战脚本](https://hamibot.com/marketplace/sp1Lc)，新版本的四人赛和双人对战答题速度和正确率已经大大提升，欢迎大家来测试新版本

**Comment by luoxuye** [comment]
> 

感谢大佬！！快被我妈烦死了。
