### ISSUE TITLE
被封七天🌚尽量少用辅助

### ISSUE THREAD

**Issue by derryck404** [dundunnp/hamibot-auto_xuexiqiangguo#731]
![Screenshot_20230425_120611.jpg](https://user-images.githubusercontent.com/53424148/234239553-f3591080-c59f-449f-a851-7844bfe0081a.jpg)

之前用auto js被警告一次，后改用网页插件+手动（两周多正常）但是今天一打开显示被封了 真的挺无语的🌚

**Comment by songjiang951130** [comment]
我是11点54

**Comment by fdq236** [comment]
惨了，你这是七天，那我的就是永久了…  哎凉凉

**Comment by fsnhljz** [comment]
我之前被警告，后来我卸载了安卓端的，用回ios的，然后用油猴js脚本，没有警告过了。

**Comment by jsj0622** [comment]
> 我之前被警告，后来我卸载了安卓端的，用回ios的，然后用油猴js脚本，没有警告过了。

电脑上的油猴JS脚本吗
