### ISSUE TITLE
为什么全手动也会收到警告

### ISSUE THREAD

**Issue by derryck404** [dundunnp/hamibot-auto_xuexiqiangguo#738]
![Screenshot_20230507_234548.jpg](https://user-images.githubusercontent.com/53424148/236688041-5145fef6-4760-4d9e-b1a9-2c7ca704aa0d.jpg)

解封之后一直全手动答题，看视频是百灵自动刷，不理解为啥还会收到警告🌚🌚

**Comment by keyseeone** [comment]
手动的话，把辅助软件卸载了吗

**Comment by derryck404** [comment]
> 手动的话，把辅助软件卸载了吗

都卸载了 也是单设备登录使用的

**Comment by derryck404** [comment]
![Screenshot_20230508_122153.jpg](https://user-images.githubusercontent.com/53424148/236733243-47f5303b-9462-4322-b85b-4e2a1c9f0c29.jpg)
又警告一次…

**Comment by McMug2020** [comment]
没卸干净？

**Comment by PeterXiaosa** [comment]
> 没卸干净？

请问下 你这边使用过程中是一直没收到警告提示吗？

**Comment by derryck404** [comment]
> > 没卸干净？
> 
> 请问下 你这边使用过程中是一直没收到警告提示吗？

我全程手动使用 当天是没有收到警告，正常获取积分，但是第二天一打开APP就收到警告提示了，而且连续两次。最近停止竞赛答题相关的刷分，暂时还没收到第三次警告

**Comment by derryck404** [comment]
> 没卸干净？

与学习强国相关的js文件夹已删除，但autojs这个APP没删（有其他项目，但在刷分时并不开启）

查看总结[Issues739](https://github.com/dundunnp/auto_xuexiqiangguo/issues/739)，目前停止答题类刷分后，3天正常，没有收到警告（每次答题都会有滑动验证，感觉是这个风险原因

**Comment by songjiang951130** [comment]
> 

有滑动验证，就很危险了

**Comment by McMug2020** [comment]
> > 没卸干净？
> 
> 请问下 你这边使用过程中是一直没收到警告提示吗？

刚开始收到过，目前一机一号，全自动学，隐藏应用列表，不再有警告
