### ISSUE TITLE
答题失败，四人赛双人赛都不行

### ISSUE THREAD

**Issue by adfnkjasd** [dundunnp/hamibot-auto_xuexiqiangguo#92]
![65e10785a1db10b3a66ae61da5aab4e](https://user-images.githubusercontent.com/39746646/147013136-b187c942-ba6f-49ca-9a4d-de799d98089c.jpg)

hamibot日志显示连接不上www.souwen123.com ，感觉有可能是网址挂了，可以ping通，但是上不去，希望考虑答题前测试连接情况，多加一份备用网址

**Comment by whhxmwhh** [comment]
哦哦。我以为是华为配置出问题呢。感谢。

**Comment by adfnkjasd** [comment]
3.2修复了 大佬牛逼
