### ISSUE TITLE
souwen123.com又好了。

### ISSUE THREAD

**Issue by lukemin** [dundunnp/hamibot-auto_xuexiqiangguo#96]
souwen123.com又好了。

**Comment by dundunnp** [comment]
配置信息的省份没有配置正确






 
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年12月24日 11:34:06
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [dundunnp/hamibot-auto_xuexiqiangguo] souwen123.com又好了。 (Issue #96)




 
souwen123.com又好了。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
